   SELECT 
       CASE
         WHEN B2_FILIAL = '01' THEN 'RS'
         WHEN B2_FILIAL = '02' THEN 'MG'
         WHEN B2_FILIAL = '03' THEN 'PR'
         WHEN B2_FILIAL = '04' THEN 'SC'
         ELSE 'OUTROS' END FILIAL,
       B2_LOCAL ARMAZEM,
       B1_PROC FORNECEDOR,
       B1_COD CODIGO,
       B1_DESC PRODUTO,
       B2_QATU QTD_FISICO,
       (B2_QATU * B1_QTELITS) LTS_FISICO,
       (B2_QATU - B2_RESERVA) QTD_DISPONIVEL,
       ((B2_QATU - B2_RESERVA) * B1_QTELITS) LTS_DISPONIVEL,
	   B2_CM1 CUSTO_CMV_PADRAO,
       CASE
         WHEN B2_CM1 > B1_CUSTD THEN
          --Round(B2_CM1 + (B2_CM1 * ((B1_PPIS + B1_PCOFINS) / 100)), 2)
		  Round(B2_CM1 * CASE WHEN B1_DESC LIKE 'LT LUST%' THEN 0.94 ELSE 1 END ,2) 
         ELSE
          --Round(B1_CUSTD + (B1_CUSTD * ((B1_PPIS + B1_PCOFINS) / 100)), 2)
		  Round(B1_CUSTD * CASE WHEN B1_DESC LIKE 'LT LUST%' THEN 0.94 ELSE 1 END ,2) 
       END CUSTO_STD,
       CASE
         WHEN B2_CM1 <> 0 THEN
          --Round(B2_CM1 + (B2_CM1 * ((B1_PPIS + B1_PCOFINS) / 100)), 2)
		  Round(B2_CM1 * CASE WHEN B1_DESC LIKE 'LT LUST%' THEN 0.94 ELSE 1 END ,2) 
         ELSE
         -- Round(B1_CUSTD + (B1_CUSTD * ((B1_PPIS + B1_PCOFINS) / 100)), 2)
		 Round(B1_CUSTD * CASE WHEN B1_DESC LIKE 'LT LUST%' THEN 0.94 ELSE 1 END ,2) 
       END CUSTO_CMV,
       ISNULL((SELECT SUM(C6_QTDVEN - C6_QTDENT)
             FROM C8O7DN_135098_PR_PD.dbo.SC6140 C6, C8O7DN_135098_PR_PD.dbo.SF4140 F4
            WHERE F4.D_E_L_E_T_ = ' '
              AND F4_ESTOQUE = 'S'
              AND F4_CODIGO = C6_TES
              AND F4_FILIAL = C6_FILIAL
              AND C6.D_E_L_E_T_ = ' '
              AND C6_LOCAL = B2_LOCAL
              AND C6_PRODUTO = B1_COD
              AND C6_BLQ <> 'R'
              AND C6_FILIAL = B2_FILIAL),
           0) DIGITADO,
      -- C8O7DN_135098_PR_PD.dbo.AT_MICHELIN_B2CUSTO2016(B1_COD, B2_LOCAL, B2_FILIAL) NEW_CUSTOB2_MICHELIN,
       B1_CABO AS SEGMENTO_PRODUTO
  FROM C8O7DN_135098_PR_PD.dbo.SB1140 B1
  INNER JOIN C8O7DN_135098_PR_PD.dbo.SB2140 B2 ON
  B2.B2_FILIAL IN ('01', '02', '03', '04')
  AND B1.B1_COD = B2.B2_COD
    AND B1.B1_FILIAL = B2.B2_FILIAL
    AND B2.D_E_L_E_T_ = ' '
    AND B2.B2_LOCAL IN ('01') 
 WHERE 

    B1.D_E_L_E_T_ = ' '
    AND B1.B1_MSBLQL <> '1'