
  SELECT 
       FILIAL, 
       ESTADO,
       CIDADE,
       TRANSPORTADORA,
       MAX(VENDEDOR) VENDEDOR,
       CODIGO,
       LOJA,
       CLIENTE,
       COUNT(DISTINCT(NUM_NOTAS)) NUM_NOTAS,
       MAX(NOTA) NOTA,
       MAX(SERIE) SERIE,
       ANO_MES ,
       MAX(EMISSAO) EMISSAO,
       SUM(PESO_BRUTO) PESO_BRUTO,
       SUM(VALOR_NF) VALOR_BRUTO,
       SUM(FATURADO) FATURADO,
       SUM(VAL_TEXACO) VAL_TEXACO,
       SUM(VAL_PNEU) VAL_PNEU,
       SUM(CUSTO) CUSTO_NFS,
       SUM(FATURADO)-SUM(CUSTO) MARGEM_VLR,
       ROUND((CASE WHEN SUM(FATURADO) = 0 THEN CASE WHEN SUM(CUSTO) > 0 THEN -100 ELSE 0 END ELSE (SUM(FATURADO)-SUM(CUSTO))/SUM(FATURADO) * 100 END),2) MARGEM1_PERC,
       F1_DOC NUM_CTE,
       F1_SERIE SER_CTE,
       F1_FORNECE FORNECEDOR,
       F1_LOJA LOJ_FOR,
       F1_DTDIGIT DATA_ENTRADA,
       MAX(DATA_ENTREGA) AS DATA_ENTREGA,
       CASE WHEN (MAX(DATA_ENTREGA) IS NULL OR MAX(DATA_ENTREGA) = '        ') THEN NULL ELSE MAX(DATA_ENTREGA) END AS DATA_ENTREGA,
       MAX(PRAZO) AS PRAZO,
       MAX(ROTA) AS ROTA,
       SUM(CUSTO_CALCULADO) CUSTO_CALCULADO,
       F1_VALBRUT VALOR_CTE,
       CASE WHEN SUM(VALOR_NF) > 0 THEN ROUND(F1_VALBRUT / SUM(VALOR_NF) * 100,2) ELSE 100 END  PERC_FRETE
  FROM (
   SELECT
       F2_FILIAL FILIAL,
       A1_COD CODIGO,
       A1_LOJA LOJA,
       A1_NOME CLIENTE,
       A1_EST ESTADO,
       A1_MUN CIDADE,
       CONCAT(F2_TRANSP , '-' , A4_NREDUZ) TRANSPORTADORA,
       F2_SERIE,F2_DOC NUM_NOTAS,
       F2_DOC NOTA,
       F2_SERIE SERIE,
       CONCAT(F2_VEND1 , '-' , A3_NREDUZ) VENDEDOR,
       SUBSTRING(F2_EMISSAO, 1, 6) ANO_MES,
       F2_EMISSAO EMISSAO,
       F2_VALBRUT VALOR_NF,
       F2_PBRUTO PESO_BRUTO,
       F2_VALFAT FATURADO,
       F2.F2_CUSTOFR CUSTO_CALCULADO,
       F1_DOC,
       F1_SERIE,
       F1_FORNECE,
       F1_LOJA,
       F1_DTDIGIT,
       F1_VALBRUT,
       ISNULL((SELECT SUM(
              CASE
                WHEN D2_XCUSTO > D2_CUSTO1
                  THEN D2_XCUSTO 
                ELSE D2_CUSTO1 
              END +D2_VALPROM+D2_VALICM+D2_VALIMP5+D2_VALIMP6)
              FROM C8O7DN_135098_PR_PD.dbo.SD2140 D2
             WHERE D2.D_E_L_E_T_ =''
               AND D2_SERIE = F2.F2_SERIE
               AND D2_DOC = F2.F2_DOC
               AND D2_LOJA = F2.F2_LOJA
               AND D2_CLIENTE = F2.F2_CLIENTE
               AND D2_FILIAL = F2_FILIAL),0) CUSTO,
       ISNULL((SELECT SUM(D2_VALBRUT)
              FROM C8O7DN_135098_PR_PD.dbo.SD2140 D2,C8O7DN_135098_PR_PD.dbo.SB1140 B1
             WHERE D2.D_E_L_E_T_ =''
               AND B1.D_E_L_E_T_ =''
               AND B1_CABO NOT IN('MIC','MOT','CON')
               AND B1_COD = D2_COD
               AND B1_FILIAL = D2_FILIAL
               AND D2_SERIE = F2.F2_SERIE
               AND D2_DOC = F2.F2_DOC
               AND D2_LOJA = F2.F2_LOJA
               AND D2_CLIENTE = F2.F2_CLIENTE
               AND D2_FILIAL = F2_FILIAL),0) VAL_TEXACO,
       ISNULL((SELECT SUM(D2_VALBRUT)
              FROM C8O7DN_135098_PR_PD.dbo.SD2140 D2,C8O7DN_135098_PR_PD.dbo.SB1140 B1
             WHERE D2.D_E_L_E_T_ =''
               AND B1.D_E_L_E_T_ =''
               AND B1_CABO IN('MIC','MOT','CON')
               AND B1_COD = D2_COD
               AND B1_FILIAL = D2_FILIAL
               AND D2_SERIE = F2.F2_SERIE
               AND D2_DOC = F2.F2_DOC
               AND D2_LOJA = F2.F2_LOJA
               AND D2_CLIENTE = F2.F2_CLIENTE
               AND D2_FILIAL = F2_FILIAL),0) VAL_PNEU,
               (SELECT MAX(ZU.ZU_DATAENT) FROM C8O7DN_135098_PR_PD.dbo.SZU140 ZU WHERE ZU.ZU_FILIAL = F2.F2_FILIAL AND ZU.ZU_NOTA = F2.F2_DOC AND ZU.ZU_SERIE = F2.F2_SERIE AND ZU.D_E_L_E_T_ = '' GROUP BY ZU_FILIAL,ZU_NOTA,ZU_SERIE) AS DATA_ENTREGA,
               (SELECT MAX(PAB.PAB_PRAZO) FROM C8O7DN_135098_PR_PD.dbo.PAB140 PAB WHERE PAB.PAB_FILIAL = '' AND PAB.PAB_CEP = A1.A1_CEP AND PAB.PAB_TRANSP = F2.F2_TRANSP AND PAB.D_E_L_E_T_ = '' GROUP BY PAB.PAB_CEP,PAB.PAB_TRANSP) AS PRAZO,
               (SELECT MAX(PAB.PAB_ROTA) FROM C8O7DN_135098_PR_PD.dbo.PAB140 PAB WHERE PAB.PAB_FILIAL = '' AND PAB.PAB_CEP = A1.A1_CEP AND PAB.PAB_TRANSP = F2.F2_TRANSP AND PAB.D_E_L_E_T_ = '' GROUP BY PAB.PAB_CEP,PAB.PAB_TRANSP) AS ROTA
  FROM C8O7DN_135098_PR_PD.dbo.SF2140 F2

  INNER JOIN C8O7DN_135098_PR_PD.dbo.SA1140 A1 
    ON  A1_FILIAL = '  '
    AND A1_LOJA = F2_LOJA
    AND A1_COD = F2_CLIENTE
    AND A1.D_E_L_E_T_ = '' 

  INNER JOIN C8O7DN_135098_PR_PD.dbo.SA4140 A4
    ON  A4_FILIAL = '  '
    AND A4_COD = F2_TRANSP
    AND A4.D_E_L_E_T_ = ''    

  INNER JOIN C8O7DN_135098_PR_PD.dbo.SA3140 A3
   ON  A3_FILIAL = '  '    
   AND A3_COD = F2_VEND1
   AND A3.D_E_L_E_T_ = ''
   
   INNER JOIN   C8O7DN_135098_PR_PD.dbo.CONDORCTEXNFS B
   ON  XCN_SERNFS = F2_SERIE
   AND XCN_CLINFS = F2_CLIENTE
   AND XCN_LOJNFS = F2_LOJA
   AND XCN_TIPNFS = F2_TIPO
   AND XCN_FIL = F2_FILIAL
   AND XCN_NUMNFS = F2_DOC
   AND XCN_EMP = '14'
   AND B.D_E_L_E_T_ = ''

   INNER JOIN   C8O7DN_135098_PR_PD.dbo.CONDORXML C
    ON C.D_E_L_E_T_ = ''
   AND C.XML_CHAVE = B.XCN_CHVCTE
   AND C.XML_REJEIT = ''
   
   INNER JOIN   C8O7DN_135098_PR_PD.dbo.SF1140 F1
   ON F1.F1_FILIAL = XCN_FIL
   AND F1_FORNECE = B.XCN_FORCTE
   AND F1_LOJA = XCN_LOJCTE
   AND F1_SERIE = XCN_SERCTE
   AND F1_DOC = XCN_NUMCTE
   AND F1_CHVNFE = XCN_CHVCTE
   AND F1.D_E_L_E_T_ = ''

 WHERE 
   F2_FILIAL IN('01','02','03','04')
   AND F2.D_E_L_E_T_ = ''
   AND F2_TIPO = 'N'
   AND F2_EMISSAO >= convert(varchar, GETDATE()-180, 112) 
   ) A
 GROUP BY 
        FILIAL,
        CODIGO,
        LOJA,
        CLIENTE,
        ESTADO,
        CIDADE,
        TRANSPORTADORA,ANO_MES,F1_DOC,F1_SERIE,F1_FORNECE,F1_LOJA,F1_DTDIGIT,F1_VALBRUT
 ORDER BY FILIAL,ESTADO,CIDADE,TRANSPORTADORA,VENDEDOR,CLIENTE

